### ISSUE TITLE
后台文章列表/文章添加相关问题

### ISSUE THREAD

**Issue by Y-A-K-E** [yue909/lemocms#2]
1,1080P分辨率/firefox 浏览器体验有点差
文章列表,列表底部有个横向滚动条.
操作按钮变成三个点 ...   (要拖开标题格间距才能看到删除按钮)

另外
文章列表,缩略图一栏那里显示标题没啥意义.
文章列表 前面个选择框 ,全选框也没啥意义.因为没有批量操作.勾选可以考虑去掉.

2,新增文章
必须填写邮箱和浏览数量是一个不太友好的体验.

后台添加文章就一个管理员,填邮箱没啥意义.
如果考虑多账号的,我觉得可以考虑自动获取后台登陆用户的账号填入.
另外浏览数量如果不指定,可以考虑指定默认为0.

3,文章编辑之后,提交不会回到列表页面,必须手动点返回才会回到列表,也是一个不太友好的体验
我提交后,就已经编辑完成了,我不需要再编辑了,我觉得编辑提交后,返回到列表页面才是相对友好的体验.

**Comment by xunni1000** [comment]
另外文章列表
缩略图图片url也是有点问题的
正确应该是

> http://test.com/storage/uploads/20191118/5b445746e24179cb2e0493327d84bfd0.jpg

但是鼠标移动上去地址却是

> http://test.com/storage/uploads/20191118%05b445746e24179cb2e0493327d84bfd0.jpg


对应数据库记录,
这个斜杠方向是不是不太对的亚子...
> /storage/uploads/20191118\5b445746e24179cb2e0493327d84bfd0.jpg

**Comment by yue909** [comment]
感谢反馈，很好的建议

**Comment by lihe6666** [comment]
感谢反馈, 很好的建议.  目前正在体验中, 接下来解决出现的问题
